# Generated by Django 5.0.6 on 2024-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('layer_type', models.CharField(choices=[('input', 'Input Layer'), ('dense', 'Dense Layer'), ('conv', 'Convolutional Layer')], max_length=10)),
                ('parameters', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layers', models.ManyToManyField(related_name='neural_networks', to='builder.layer')),
            ],
        ),
    ]
